apiVersion: apps/v1
kind: Deployment
metadata:
  name: cncf-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cncf-dashboard
  template:
    metadata:
      labels:
        app: cncf-dashboard
    spec:
      containers:
      - name: cncf-dashboard
        image: ${IMAGE}
        imagePullPolicy: IfNotPresent
      - name: redis
        image: ${REDIS_IMAGE}
        ports:
        - containerPort: 8081
        env:
          - name: DATABASE_URL
            value: ${DATABASE_URL_DOCKER}
---
apiVersion: v1
kind: Service
metadata:
  name: cncf-service
spec:
  selector:
    app: cncf-dashboard
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8081
  type: NodePort
