version: '3'
services:
  app:
    build:
      context: . 
    ports:
      - "8082:8081"
    environment:
      - REDIS_HOST_PORT=${REDIS_HOST_PORT}
    depends_on:
      - redis  
  redis:
    image: {REDIS_IMAGE}
