name: Continuous Integration (CI)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'
    - name: Change to Server Directory
      run: cd server
    - name: Install Dependencies
      run: npm install
    - name: Run Tests
      run: npm test
    - name: Build
      run: npm run build
